<?php
/*
 * Shared front-end preview data for the Ruleset Hub and room detail page.
 * No data in this file represents a real Match, Steam identity or published contract.
 */

$lobbyRooms = [
  [
    'room_id' => 'demo-room-001',
    'game_room_id' => '0fPMom7OsZwjVp1jie7s8qVlKTOPYyBI',
    'room_name' => '西瓜版公開對戰',
    'host' => 'Way',
    'cp' => 1660,
    'ruleset' => '1.26 西瓜版',
    'ruleset_version_id' => 'ulgg-watermelon-126@1.26.0',
    'version' => '1.26.0',
    'cost_limit' => '60C',
    'region' => 'STEAM',
    'channel' => 'room2',
    'visibility' => 'PUBLIC',
    'waiting_minutes' => 3,
    'status' => 'WAITING',
    'created_at' => '展示資料：3 分鐘前',
  ],
  [
    'room_id' => 'demo-room-002',
    'room_name' => '標準規則交流房',
    'host' => 'Noir',
    'cp' => 1570,
    'ruleset' => '眼鏡99版',
    'ruleset_version_id' => 'ulgg-standard-demo@1.0.0',
    'version' => '1.0.0',
    'cost_limit' => '待確認',
    'region' => 'STEAM',
    'channel' => 'room4',
    'visibility' => 'PUBLIC',
    'waiting_minutes' => 7,
    'status' => 'WAITING',
    'created_at' => '展示資料：7 分鐘前',
  ],
  [
    'room_id' => 'demo-room-003',
    'room_name' => 'Open Match 練習',
    'host' => 'Ruka',
    'cp' => 1535,
    'ruleset' => '眼鏡99版',
    'ruleset_version_id' => 'community-open-match@0.9.2',
    'version' => '0.9.2',
    'cost_limit' => '58C',
    'region' => 'DMM',
    'channel' => 'room2',
    'visibility' => 'PUBLIC',
    'waiting_minutes' => 12,
    'status' => 'WAITING',
    'created_at' => '展示資料：12 分鐘前',
  ],
  [
    'room_id' => 'demo-room-004',
    'room_name' => '新手友善切磋',
    'host' => 'Meteor',
    'cp' => 1620,
    'ruleset' => '眼鏡99版',
    'ruleset_version_id' => 'community-beginner@0.8.0',
    'version' => '0.8.0',
    'cost_limit' => '展示規則',
    'region' => 'STEAM',
    'channel' => 'room2',
    'visibility' => 'PUBLIC',
    'waiting_minutes' => 18,
    'status' => 'WAITING',
    'created_at' => '展示資料：18 分鐘前',
  ],
];

$rulesetVersions = [
  [
    'rule_set_id' => 'ulgg/glasses-99-demo',
    'rule_version_id' => 'ulgg-glasses-99-demo@0.1.0',
    'name' => 'ULGG Glasses 99 Custom Match',
    'name_zh' => '眼鏡99版',
    'version' => '0.1.0',
    'tier' => 'OFFICIAL',
    'lifecycle_status' => 'PUBLISHED',
    'schema_version' => '1.0',
    'content_hash' => 'sha256:demo-ulgg-standard-1-0-0-not-a-real-hash',
    'publisher' => 'ULGG Demo',
    'published_at' => '2026-07-29',
    'rules' => [
      '艾伯李斯特：L1 COST 99。',
      '史特靈：L5 COST 24；R1 COST 23。',
      '沃蘭德：L4 COST 22。',
    ],
    'full_rules' => [
      '隊伍由三名角色組成。',
      '禁止於同一隊伍中使用重複角色。',
      '艾伯李斯特：L1 COST 99。',
      '史特靈：L5 COST 24；R1 COST 23。',
      '沃蘭德：L4 COST 22。',
      '利恩：L4 COST 16。',
      '出葉：R2 COST 22。',
      '里斯：L3 COST 16；L4 COST 17。',
      '蕾塔：L5 COST 23；R1 COST 22。',
      '庫恩：R4 COST 29。',
      '路德：R5 COST 29。',
      '米利安：R4 COST 25；R5 COST 27。',
      '威廉：R5 COST 28。',
      '尤莉卡：R4 COST 27。',
      '未列入本規則版本的角色 COST 與技能效果，維持原始設定。',
      '本規則版本一經發布即固定，不得直接修改；後續調整須建立新的規則表版本。',
    ],
    /* 'full_rules' => [
      '隊伍由三名角色組成，隊伍總 COST 上限為 60。',
      '禁止於同一隊伍中使用重複角色。',
      '史特靈：L5 COST 24；R1 COST 23。',
      '沃蘭德：L4 COST 22；「萬物主宰」及「EX 萬物主宰」不得於近距離發動。',
      '利恩：L4 COST 16。',
      '出葉：R2 COST 22。',
      '里斯：L3 COST 16；L4 COST 17。',
      '蕾塔：L5 COST 23；R1 COST 22。',
      '庫恩：R4 COST 29；「EX 罪業的蠢動」不得於近距離發動。',
      '路德：R5 COST 29。',
      '米利安：R4 COST 25；R5 COST 27。',
      '威廉：R5 COST 28。',
      '尤莉卡：R4 COST 27。',
      '梅莉：「綿羊幻夢」及「EX 綿羊幻夢」不得於近距離發動。',
      '未列入本規則版本的角色 COST 與技能效果，維持原始設定。',
      '本規則版本一經發布即固定，不得直接修改；後續調整須建立新的 Ruleset Version。',
    ], */
  ],
  [
    'rule_set_id' => 'ulgg/watermelon-126',
    'rule_version_id' => 'ulgg-watermelon-126@1.26.0',
    'name' => 'Watermelon 1.26',
    'name_zh' => '1.26 西瓜版',
    'version' => '1.26.0',
    'tier' => 'COMMUNITY',
    'lifecycle_status' => 'DRAFT',
    'schema_version' => '1.0',
    'content_hash' => 'sha256:demo-watermelon-126-not-a-real-hash',
    'publisher' => 'ULGG Community Demo',
    'published_at' => '2026-07-24',

    'rules' => [
      '西瓜帽 DEF+8 COST 8。',
      '只有羅索才能配戴。',
      '遊玩時需配戴西瓜皮安全帽。',
    ],

    'full_rules' => [
      '禁止於同一隊伍中使用重複角色，雙胞胎也不行。',
      '出場時需自備西瓜一顆。',
      '沃蘭德：L4 COST 22；「萬物主宰」及「EX 萬物主宰」不得於近距離發動，除非對手先說請。',
      '出牌時不得同時剝西瓜籽。',
      '瀏海歪掉時 COST 額外加 1。',
      '禁止把西瓜當作事件卡使用。',
      '庫恩：R4 COST 29；「EX 罪業的蠢動」不得於近距離發動，蠢動可以，但不要太明顯。',
      '騎車前往對戰時必須配戴西瓜皮安全帽。',
      '連敗三場後可以申請西瓜汁一杯，但主辦方不負責提供。',
      '嚴禁在計算 COST 時偷偷使用計算機，除非真的算不出來。',
      '梅莉：「綿羊幻夢」及「EX 綿羊幻夢」不得於近距離發動，也不得在夢裡偷改 COST。',
      '上廁所期間不得食用西瓜，違者本回合移動力減 1。',
      '西瓜必須切片食用，直接拿湯匙挖者視為自由派玩家，不予處分。',
      '對戰中喊出「這把靠賽」三次者，系統將自動判定你很誠實。',
      '未列入本規則版本的角色 COST 與技能效果，維持原始設定；未列入的西瓜行為由現場裁判自由心證。',
      '本規則版本一經發布即固定，不得直接修改；後續若西瓜成熟度有變，須建立新的 Ruleset Version。',
    ],
  ],
];

foreach ($rulesetVersions as &$rulesetVersion) {
  $rulesetVersion['official_bp_eligible'] =
    $rulesetVersion['tier'] === 'OFFICIAL'
    && $rulesetVersion['lifecycle_status'] === 'PUBLISHED';
}
unset($rulesetVersion);

$cpLeaderboardDemo = [
  [
    'rank' => 1,
    'player_name' => '古魯瓦爾多',
    'cp' => 1824,
    'wins' => 18,
    'losses' => 7,
    'win_rate' => 72.0,
    'trend' => 'UP',
    'trend_value' => 42,
  ],
  [
    'rank' => 2,
    'player_name' => '艾伯李斯特',
    'cp' => 1796,
    'wins' => 16,
    'losses' => 8,
    'win_rate' => 66.7,
    'trend' => 'UP',
    'trend_value' => 28,
  ],
  [
    'rank' => 3,
    'player_name' => '艾依查庫',
    'cp' => 1712,
    'wins' => 14,
    'losses' => 9,
    'win_rate' => 60.9,
    'trend' => 'DOWN',
    'trend_value' => 12,
  ],
  [
    'rank' => 4,
    'player_name' => '阿貝爾',
    'cp' => 1668,
    'wins' => 12,
    'losses' => 10,
    'win_rate' => 54.5,
    'trend' => 'UP',
    'trend_value' => 9,
  ],
  [
    'rank' => 5,
    'player_name' => '利恩',
    'cp' => 1615,
    'wins' => 10,
    'losses' => 11,
    'win_rate' => 47.6,
    'trend' => 'SAME',
    'trend_value' => 0,
  ],
];
